name: "[CI]Test Docker Image CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

#    runs-on: ubuntu-22.04-arm
    runs-on: [ self-hosted, ARM64, macOS ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Unit Tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-asyncio
        pytest -m unit --maxfail=1 --disable-warnings -v

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and Push the APP Docker image
      run: |
        docker build . --file Dockerfile_test --tag ghcr.io/${{ github.repository_owner }}/xp_cnjoke_test:latest
        docker push ghcr.io/${{ github.repository_owner }}/xp_cnjoke_test:latest
