# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform Deploy Kind Cluster'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (optional). If empty, value from version.txt will be used'
        required: false
        default: ''

env:
  TERRAFORM_DIR: terraform
  APP_NAMESPACE: xp
  ARGOCD_NAMESPACE: argocd

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [ self-hosted, ARM64, macOS ]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Delete existing Kind cluster
      run: kind delete cluster --name cnjoke-cluster || true

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=$TERRAFORM_DIR init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform -chdir=$TERRAFORM_DIR fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=$TERRAFORM_DIR plan -input=false

    - name: Terraform Apply
      run: terraform -chdir=$TERRAFORM_DIR apply -auto-approve -input=false

    - name: Init Kind Cluster
      run: kubectl config use-context kind-cnjoke-cluster

    - name: Create ghcr.io secret
      run: |
        kubectl create namespace $APP_NAMESPACE || true
        kubectl -n $APP_NAMESPACE create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.repository_owner }} \
          --docker-password=${{ secrets.GHCR_TOKEN }} \
          --docker-email=none \

    - name: Install argocd
      run: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
        helm install argocd argo/argo-cd -n argocd --create-namespace

    - name: Inject Version into app-deployment
      run: |
        DEFAULT_VERSION=$(cat version.txt)
        if [[ -n "${{ github.event.inputs.version }}" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=$DEFAULT_VERSION
        fi
        echo "Using version: $VERSION"
        jinja2 k8s_deployment/app-deployment.yaml.j2 -D version=$VERSION > k8s_deployment/app-deployment.yaml
        echo $(cat k8s_deployment/app-deployment.yaml)

    - name: Deploy Application CD pipeline in argocd
      run: |
        kubectl apply -f cicd/argocd-project.yaml
